- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.scss
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/styles/components/feature-blocks.scss
- embc-app/ClientApp/src/styles/components/summary.scss
- embc-app/ClientApp/start.sh
- embc-app/ClientApp/stop.sh
* thank you page skeleton
* additional style tweaks
> Frontend changes

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.component.html
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/home/home.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration.component.html
- embc-app/ClientApp/src/app/shared/components/footer/footer.component.scss
- embc-app/ClientApp/src/app/volunteer-login/volunteer-login.component.html
- embc-app/ClientApp/src/app/volunteer-login/volunteer-login.component.spec.ts
- embc-app/ClientApp/src/app/volunteer-login/volunteer-login.component.ts
Number 41 mentioned the requirement for mobile breakpoints in the self-registration. These changes are minor bug fixes for bootstrap break points. It also makes a fix for broken sticky bootstrap footers.
> Breakpoint bug fixes

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.component.html
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/home/home.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration.component.html
- embc-app/ClientApp/src/app/shared/components/footer/footer.component.scss
- embc-app/ClientApp/src/app/volunteer-login/volunteer-login.component.html
- embc-app/ClientApp/src/app/volunteer-login/volunteer-login.component.spec.ts
- embc-app/ClientApp/src/app/volunteer-login/volunteer-login.component.ts
> Volunteer login dummy components

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/core/services/registration.service.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration.component.spec.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration.component.ts
- embc-app/ClientApp/src/app/volunteer-dashboard/volunteer-dashboard.component.html
- embc-app/ClientApp/src/app/volunteer-dashboard/volunteer-dashboard.component.scss
This is a static shell version of the form layout for the "Add an Evacuee" form. I plan on breaking this form out into components that can be reused before connecting the data
> Evacuee add form

- embc-app/ClientApp/src/app/volunteer-dashboard/volunteer-dashboard.component.ts
Fix for a condition where a null family member can cause an error where the application loses state. Not what we want during the demo. I think that when the data takes form more from the API we can work on testing.
@asanchezr
> Fix unreducer null

- embc-app/ClientApp/API.md
A document that tracks our current API and the expected endpoints. This makes a target for front and backend communication.
@asanchezr
> Add API Endpoint Markdown Worksheet

- embc-app/Controllers/IncidentTasksController.cs
- embc-app/Controllers/RegistrationsController.cs
- embc-app/DataInterfaces/IDataInterface.cs
- embc-app/DataInterfaces/SqliteDataInterface.cs
- embc-app/DataInterfaces/ViewModelConversions.IncidentTask.cs
- embc-app/SeedData/IncidentTasks.json
- embc-app/Seeders/CommunitySeeder.cs
- embc-app/Seeders/IncidentTaskSeeder.cs
- embc-app/Seeders/RegionSeeder.cs
- embc-app/Seeders/RegionalDistrictSeeder.cs
- embc-app/Sqlite.Models/IncidentTask.cs
- embc-app/ViewModels/IncidentTask.cs
- embc-app/embc-app.csproj
* Add wildcard *json to csproj for SeedData directory
* Add controller and CRUD methods for incident tasks
* Add seeder for incident tasks
* Incident task view model conversion
> Backend incident tasks

- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration.component.html
- embc-app/ClientApp/src/app/home/home.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration.component.html
- embc-app/ClientApp/src/app/volunteer-dashboard/volunteer-dashboard.component.html
Content for the parts that we have. I will be keeping this branch alive so that I can copy/paste new content in when we get new verbiage.
@asanchezr
> Content blast

- embc-app/Controllers/RegistrationsController.cs
- embc-app/DataInterfaces/IDataInterface.cs
- embc-app/DataInterfaces/SqliteDataInterface.cs
- embc-app/Startup.cs
- embc-app/Utils/IQueryableExtensions.cs
- embc-app/Utils/PaginatedList.cs
- embc-app/Utils/PaginatedListExtensions.cs
- embc-app/Utils/PaginationLink.cs
- embc-app/Utils/PaginationMetadata.cs
- embc-app/Utils/SearchQueryParameters.cs
- embc-app/Utils/SearchQueryParametersExtensions.cs
- embc-app/embc-app.csproj
* Enable searching by Evacuee last name, Task Number, etc
* Support pagination of results (e.g. `?limit=10&offset=0`)
* Support sorting of results (e.g. `?sort=headofhousehold.lastname`)
> Evacuee Simple Search (Backend)

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/core/services/volunteer.service.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor-confirmation/ess-editor-confirmation.component.html
- embc-app/ClientApp/src/app/ess-editor/ess-editor-confirmation/ess-editor-confirmation.component.spec.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor-confirmation/ess-editor-confirmation.component.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor-one/ess-editor-one.component.html
- embc-app/ClientApp/src/app/ess-editor/ess-editor-one/ess-editor-one.component.spec.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor-one/ess-editor-one.component.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor.component.html
- embc-app/ClientApp/src/app/ess-editor/ess-editor.component.spec.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor.component.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor.module.ts
- embc-app/ClientApp/src/app/ess-editor/index.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration.module.ts
- embc-app/ClientApp/src/app/evacuee-registration/index.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.html
UI elements mostly complete. Need to switch to ngrx to handle UI more.
> Legal entity volunteer editor

- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-confirmation/evacuee-registration-confirmation.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-confirmation/evacuee-registration-confirmation.component.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/store/registration/registration.reducer.ts
- embc-app/ClientApp/src/app/store/volunteer/volunteer.actions.ts
- embc-app/ClientApp/src/app/store/volunteer/volunteer.reducer.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.html
Branch named wrong. I didn't have access to jira to take a vertical slice. After our discussion I will try to steer away from this area of the application. This is the ngrx in the evacuee registration. Next I will do this in the legal entity volunteer state with the volunteer.
@asanchezr
> Legal entity volunteer state

- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
@asanchezr A fix for the form behaviour loss.
> Evacuee form patch

- embc-app/Controllers/RegistrationsController.cs
- embc-app/DataInterfaces/SqliteDataInterface.cs
- embc-app/Startup.cs
- embc-app/Utils/EmailSender.cs
- embc-app/Utils/IEmailSender.cs
- embc-app/ViewModels/HeadOfHousehold.cs
- embc-app/ViewModels/Registration.cs
* Basic email sending and hookup to registration POST
* Random ESS number and registration completed email template
> Be email on registration

- embc-app/ClientApp/src/app/core/services/volunteer.service.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor-confirmation/ess-editor-confirmation.component.html
- embc-app/ClientApp/src/app/ess-editor/ess-editor-confirmation/ess-editor-confirmation.component.ts
- embc-app/ClientApp/src/app/ess-editor/ess-editor-one/ess-editor-one.component.html
- embc-app/ClientApp/src/app/ess-editor/ess-editor-one/ess-editor-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/shared/components/footer/footer.component.html
- embc-app/ClientApp/src/app/store/index.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.html
- embc-app/ClientApp/src/app/tester-page/tester-page.component.ts
@asanchezr 
this completes front end functionality on the add edit volunteer. Only testing and tweaks needed.
> Volunteer ngrx state integration

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.html
- embc-app/ClientApp/src/app/volunteer-useful-information/volunteer-useful-information.component.html
- embc-app/ClientApp/src/app/volunteer-useful-information/volunteer-useful-information.component.spec.ts
- embc-app/ClientApp/src/app/volunteer-useful-information/volunteer-useful-information.component.ts
Useful information content update. No link to this content yet. We need a top navigation bar to get here.
@asanchezr
> Volunteer useful information

- embc-app/ClientApp/src/app/app.component.html
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/volunteer-navbar/volunteer-navbar.component.html
- embc-app/ClientApp/src/app/volunteer-navbar/volunteer-navbar.component.spec.ts
- embc-app/ClientApp/src/app/volunteer-navbar/volunteer-navbar.component.ts
The volunteer navbar lets a user access the information component. However to see this component the user needs to be logged in and the application state needs to remember that they are logged in.
> Volunteer navbar

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/core/models/registration.model.ts
- embc-app/ClientApp/src/app/core/services/registration.service.ts
- embc-app/ClientApp/src/app/evacuee-summary/evacuee-summary.component.html
- embc-app/ClientApp/src/app/evacuee-summary/evacuee-summary.component.spec.ts
- embc-app/ClientApp/src/app/evacuee-summary/evacuee-summary.component.ts
- embc-app/ClientApp/src/app/store/registration/registration.reducer.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.html
@asanchezr 
This summary page shows information from the registration service. Building the modal is part of another story to do with auditing. 
"As an administrator* I would like to collect information about why a volunteer is accessing an evacuee record so that I can ensure that the data is being accessed correctly." This requires separate data handling. For now I have put in a javascript "scare" message.
> Evacuee summary page

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/address-selector.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/bc-address/bc-address.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/other-address/other-address.component.ts
- embc-app/ClientApp/src/app/shared/utils/form-utils.ts
- embc-app/ClientApp/src/app/shared/utils/index.ts
- embc-app/ClientApp/src/app/shared/validation/custom.validators.ts
- embc-app/ClientApp/src/app/shared/validation/validation.helper.ts
- Validate **required** fields
- Validation rules (via custom validator class) for:
- Date of Birth
- Email address 
- BC phone numbers
> Frontend validation for Self-Registrations

- sql-server/Dockerfile.centos
- sql-server/README.md
- sql-server/docker-compose.yml
- sql-server/start.sh
- sql-server/stop.sh
* Update `Dockerfile.centos` with latest changes from Microsoft's repo.
* Create `docker-compose.yml` and start/stop scripts for local development
> Docker support for MS-SQL Server

- embc-app/ClientApp/src/app/core/models/meta-volunteers.ts
- embc-app/ClientApp/src/app/core/services/volunteer.service.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.ts
- embc-app/ClientApp/src/app/volunteer-team-dashboard/volunteer-team-dashboard.component.html
- embc-app/ClientApp/src/app/volunteer-team-dashboard/volunteer-team-dashboard.component.ts
This is search functionality on the volunteer list. This builds.
@asanchezr
> Embcess 128

- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-confirmation/admin-add-task-number-confirmation.component.html
- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-one/admin-add-task-number-one.component.html
- embc-app/ClientApp/src/app/admin-dashboard/admin-dashboard.component.html
- embc-app/ClientApp/src/app/admin-dashboard/admin-dashboard.component.ts
- embc-app/ClientApp/src/app/admin-dashboard/admin-dashboard.module.ts
- embc-app/ClientApp/src/app/admin-dashboard/admin-evacuees/admin-evacuees.component.html
- embc-app/ClientApp/src/app/admin-dashboard/admin-evacuees/admin-evacuees.component.spec.ts
- embc-app/ClientApp/src/app/admin-dashboard/admin-evacuees/admin-evacuees.component.ts
- embc-app/ClientApp/src/app/admin-dashboard/admin-organizations/admin-organizations.component.html
- embc-app/ClientApp/src/app/admin-dashboard/admin-organizations/admin-organizations.component.spec.ts
- embc-app/ClientApp/src/app/admin-dashboard/admin-organizations/admin-organizations.component.ts
- embc-app/ClientApp/src/app/admin-dashboard/admin-task-numbers/admin-task-numbers.component.html
- embc-app/ClientApp/src/app/admin-dashboard/admin-task-numbers/admin-task-numbers.component.spec.ts
- embc-app/ClientApp/src/app/admin-dashboard/admin-task-numbers/admin-task-numbers.component.ts
- embc-app/ClientApp/src/app/admin-dashboard/index.ts
- embc-app/ClientApp/src/app/admin-navbar/admin-navbar.component.html
- embc-app/ClientApp/src/app/admin-navbar/admin-navbar.component.spec.ts
- embc-app/ClientApp/src/app/admin-navbar/admin-navbar.component.ts
- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/shared/components/search/interfaces.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.html
- embc-app/ClientApp/src/app/volunteer-team-dashboard/volunteer-team-dashboard.component.html
Ready for pull. Admin dashboard routing
> Embcess 140

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.ts
- embc-app/ClientApp/tslint.json
> Users must consent to self-register.

- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.scss
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
Cleanup and dealing with merge conflicts
> Frontend validation

- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-confirmation/admin-add-task-number-confirmation.component.ts
- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-one/admin-add-task-number-one.component.html
- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-one/admin-add-task-number-one.component.ts
- embc-app/ClientApp/src/app/admin-dashboard/admin-task-numbers/admin-task-numbers.component.html
- embc-app/ClientApp/src/app/admin-dashboard/admin-task-numbers/admin-task-numbers.component.ts
- embc-app/ClientApp/src/app/app-routing.module.ts
> Admin can add, remove task numbers and view list of tasks.

- embc-app/ClientApp/package.json
- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/core/guards/logged-in.guard.ts
- embc-app/ClientApp/src/app/core/guards/redirect.guard.ts
- embc-app/ClientApp/src/index.html
Also fix `base-href` in index.html
> Add special route to redirect to external links. 

- embc-app/ClientApp/src/app/core/models/registration.model.ts
- embc-app/ClientApp/src/app/core/models/user.model.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-confirmation/evacuee-registration-confirmation.component.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.ts
- embc-app/ClientApp/src/app/shared/components/search/evacuee-search-results/evacuee-search-results.component.html
- embc-app/ClientApp/src/app/shared/components/search/evacuee-search-results/evacuee-search-results.component.ts
Fixes for:
* EMBCESS-395 registration, completion dates missing
* After finalizing user still says "finalize" even through it has a task number
> Frontent UAT bug fixes

- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-one/admin-add-task-number-one.component.html
- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-one/admin-add-task-number-one.component.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/bc-address/bc-address.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/other-address/other-address.component.ts
- embc-app/ClientApp/src/app/shared/utils/form-utils.ts
Dropdowns now work when flowing data into the form
> EMBCESS-427 no family relationship when finalizing

- embc-app/ClientApp/src/app/home/home.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/useful-information-content/useful-information-content.component.html
- embc-app/ClientApp/src/app/volunteer-dashboard/volunteer-dashboard.component.html
Verbiage change and open all links in new windows.
> Social services

- README.md
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-confirmation/evacuee-registration-confirmation.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/shared/components/address-form/address-selector.component.ts
* EMBCESS-394 no address when editing/finalizing
* EMBCESS-434 Phone numbers - Primary and alternate
* Fix link to PROD link in README.md
> Frontent UAT fixes

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
Self registration requires user interaction to complete registration.
> update null state

- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-evacuee/add-evacuee.component.html
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-organization/add-organization.component.html
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-task-number/add-task-number.component.html
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-user/add-user.component.html
- embc-app/ClientApp/src/app/store/registration/registration.reducer.ts
> Save state of restricted access checkbox bug

- embc-app/ClientApp/src/app/admin-dashboard/admin-dashboard.component.html
- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-user/add-user.component.html
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-user/add-user.component.ts
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.html
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.ts
- embc-app/ClientApp/src/app/volunteer-team-dashboard/volunteer-team-dashboard.component.html
- embc-app/ClientApp/src/app/volunteer-team-dashboard/volunteer-team-dashboard.component.ts
- tested as 'local-authority' and 'provincial-admin'
- works for add user, cancel, save, save and add another, etc
> updated volunteer add/edit/cancel routing

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/evacuee-summary-page/evacuee-summary-page.component.html
- embc-app/ClientApp/src/app/evacuee-summary-page/evacuee-summary-page.component.spec.ts
- embc-app/ClientApp/src/app/evacuee-summary-page/evacuee-summary-page.component.ts
- embc-app/ClientApp/src/app/evacuee-summary/evacuee-summary.component.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.html
This adds a page for viewing information without editing. Eventually it will host the deactivate button.
Passes build
> Summary page

- embc-app/ClientApp/src/app/core/models/list-result.ts
- embc-app/ClientApp/src/app/core/models/organization.model.ts
- embc-app/ClientApp/src/app/organization-list/organization-list.component.html
- embc-app/ClientApp/src/app/organization-list/organization-list.component.ts
- embc-app/ClientApp/src/app/shared/components/pagination-summary/pagination-summary.component.spec.ts
- embc-app/ClientApp/src/app/shared/components/pagination-summary/pagination-summary.component.ts
- embc-app/ClientApp/src/app/shared/shared.module.ts
* Finish up the rest of pending items on the Organizations list page
* Create component to display "1 - 10 of 500 results" 
* Implement filter organizations by selected community (drop-down list)
> EMBCESS-142 Organization List

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.component.ts
- embc-app/ClientApp/src/app/home/home.component.ts
- embc-app/ClientApp/src/app/organization-list/organization-list.component.html
- embc-app/ClientApp/src/app/organization-maker/organization-maker.component.html
- embc-app/ClientApp/src/app/organization-maker/organization-maker.component.ts
- embc-app/ClientApp/src/app/volunteer-list/volunteer-list.component.html
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.html
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.ts
> implementation of org users

- embc-app/ClientApp/.dockerignore
- embc-app/ClientApp/.gitignore
- embc-app/ClientApp/package-lock.json
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
Fix for bug **EMBCESS-451:** 
Family information dropdown and mailing address selection "yes" are being lost when clicking "edit registration" button.
Also, fixed the docker build after `@ng-bootstrap` was added
> Frontend bug fixes

- embc-app/ClientApp/src/app/core/models/incident-task.model.ts
- embc-app/ClientApp/src/app/core/services/incident-task.service.ts
- embc-app/ClientApp/src/app/task-number-list/task-number-list.component.html
- embc-app/ClientApp/src/app/task-number-list/task-number-list.component.ts
- embc-app/ClientApp/src/app/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/task-number-maker/task-number-maker.component.ts
As a provincial employee, I want to see the number of evacuees associated with an incident so that I can determine the overall size of incidents.
> Implement story EMBCESS-372

- embc-app/ClientApp/src/app/admin-dashboard/admin-dashboard.component.html
- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/shared/components/side-box-info/side-box-info.component.ts
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-evacuee/add-evacuee.component.html
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-evacuee/add-evacuee.component.ts
As a provincial admin, I want to be able to click on the side bar box to add an Evacuee
> Fix for EMBCESS-481

- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-one/admin-add-task-number-one.component.html
- embc-app/ClientApp/src/app/admin-add-task-number/admin-add-task-number-one/admin-add-task-number-one.component.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/organization-list/organization-list.component.html
- embc-app/ClientApp/src/app/organization-list/organization-list.component.ts
- embc-app/ClientApp/src/app/organization-maker/organization-maker.component.html
- embc-app/ClientApp/src/app/organization-maker/organization-maker.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/address-selector.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/bc-address/bc-address.component.ts
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.html
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.scss
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.spec.ts
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.ts
- embc-app/ClientApp/src/app/shared/shared.module.ts
- embc-app/ClientApp/src/app/task-number-list/task-number-list.component.html
- embc-app/ClientApp/src/app/task-number-list/task-number-list.component.ts
- embc-app/ClientApp/src/app/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.ts
- embc-app/ClientApp/src/styles/_defaults.scss
-added "communities select" typeahead component
-replaced communities dropdowns with communities-select component
-passed in placeholder for special cases
-changed 1 800 to 1-800
-added "show list" button to input
> added Communities combobox component

- embc-app/ClientApp/src/app/admin-dashboard/admin-dashboard.component.html
- embc-app/ClientApp/src/app/admin-dashboard/admin-dashboard.component.ts
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.ts
- embc-app/ClientApp/src/app/shared/components/side-boxes/collection-notice/collection-notice.component.html
- embc-app/ClientApp/src/app/shared/components/side-boxes/collection-notice/collection-notice.component.spec.ts
- embc-app/ClientApp/src/app/shared/components/side-boxes/collection-notice/collection-notice.component.ts
- embc-app/ClientApp/src/app/shared/components/side-boxes/index.ts
- embc-app/ClientApp/src/app/shared/shared.module.ts
By clicking submit the evacuee consents to collection notice.
> Collection notice updates

- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.scss
- embc-app/ClientApp/src/app/shared/components/address-form/bc-address/bc-address.component.ts
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.scss
-deleted some extra 'required' classes
-added some missing 'required' classes
-added missing 'invalid-feedback' styling
-added missing 'is-invalid' styling
> Communities combobox styling

- embc-app/ClientApp/src/app/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/evacuee-summary-page/evacuee-summary-page.component.html
- embc-app/ClientApp/src/app/evacuee-summary/evacuee-summary.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/shared/components/header/header.component.html
- embc-app/ClientApp/src/app/shared/components/search/evacuee-search-results/evacuee-search-results.component.html
- embc-app/ClientApp/src/app/shared/components/side-boxes/add-evacuee/add-evacuee.component.html
These are a collection of simple text changes.
> Content changes

- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.html
- embc-app/ClientApp/src/app/evacuee-registration/evacuee-registration-one/evacuee-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.ts
- embc-app/ClientApp/src/app/shared/components/side-boxes/collection-notice/collection-notice.component.html
Thissubmits canada and also includes response to "move the text to the top of the form" for consent verbiage on submissions pages.
> Missing Canada from submission

- embc-app/Controllers/IncidentTasksController.cs
- embc-app/Controllers/OrganizationsController.cs
- embc-app/Controllers/RegistrationsController.cs
- embc-app/Controllers/UsersController.cs
- embc-app/Controllers/VolunteersController.cs
> Revert " Locked down APIs"

- embc-app/Controllers/IncidentTasksController.cs
- embc-app/Controllers/OrganizationsController.cs
- embc-app/Controllers/RegistrationsController.cs
- embc-app/Controllers/UsersController.cs
- embc-app/Controllers/VolunteersController.cs
> Revert "Revert " Locked down APIs""

- embc-app/Controllers/IncidentTasksController.cs
- embc-app/Controllers/OrganizationsController.cs
- embc-app/Controllers/RegistrationsController.cs
- embc-app/Controllers/UsersController.cs
- embc-app/Controllers/VolunteersController.cs
> Revert "Revert "Revert " Locked down APIs"""

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.component.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/core/core.module.ts
- embc-app/ClientApp/src/app/core/http-interceptors/unauthorized.interceptor.ts
- embc-app/ClientApp/src/app/session-expired/session-expired.component.html
- embc-app/ClientApp/src/app/session-expired/session-expired.component.scss
- embc-app/ClientApp/src/app/session-expired/session-expired.component.spec.ts
- embc-app/ClientApp/src/app/session-expired/session-expired.component.ts
This is Alejandro's work after some testing and a bit of tweaking.
> Frontend kill session

- embc-app/ClientApp/src/app/app.component.html
- embc-app/ClientApp/src/app/organization-maker/organization-maker.component.ts
- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.ts
- embc-app/ClientApp/src/app/shared/components/notification-banner/notification-banner.component.html
- embc-app/ClientApp/src/app/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/top-navigation/top-navigation.component.html
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.ts
Alerts show on submissions in maker components.
> Notification integration

- embc-app/ClientApp/src/app/app.component.scss
- embc-app/ClientApp/src/app/home/home.component.scss
- embc-app/ClientApp/src/app/self-registration/self-registration-error/self-registration-error.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.scss
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
- embc-app/ClientApp/src/app/shared/components/form-field/form-field.component.scss
- embc-app/ClientApp/src/styles-font.scss
- embc-app/ClientApp/src/styles.scss
- added autocomplete property to text inputs
- added 'id's to inputs and 'for's to labels
- updated layout and styles
- added missing global styles + used some variables
> cleaned up self reg form

- embc-app/ClientApp/src/app/organization-list/organization-list.component.html
- embc-app/ClientApp/src/app/organization-maker/organization-maker.component.html
- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/bc-address/bc-address.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/other-address/other-address.component.ts
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.html
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.ts
- embc-app/ClientApp/src/app/task-number-list/task-number-list.component.html
- embc-app/ClientApp/src/app/task-number-maker/task-number-maker.component.html
- fixed misc Registration Maker form fields
- fixed labels
- fixed styling
- disabled autocomplete on applicable inputs
- cleared some sub-fields when parent fields are changed
> fixed misc Registration Maker UI

- embc-app/ClientApp/src/app/shared/components/search/evacuee-search-results/evacuee-search-results.component.html
- embc-app/ClientApp/src/app/shared/components/search/evacuee-search-results/evacuee-search-results.component.scss
- embc-app/ClientApp/src/app/shared/components/search/evacuee-search-results/evacuee-search-results.component.ts
-displayed city,province,country if Other Address
-fixed table layout
> fixed "Evacuated From"

- README.md
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/core/services/watchdog.service.ts
- embc-app/ClientApp/src/app/shared/modals/clothing-rates/clothing-rates.component.html
- embc-app/ClientApp/src/app/shared/modals/clothing-rates/clothing-rates.component.scss
- embc-app/ClientApp/src/app/shared/modals/clothing-rates/clothing-rates.component.spec.ts
- embc-app/ClientApp/src/app/shared/modals/clothing-rates/clothing-rates.component.ts
- embc-app/ClientApp/src/app/shared/modals/food-rates/food-rates.component.html
- embc-app/ClientApp/src/app/shared/modals/food-rates/food-rates.component.scss
- embc-app/ClientApp/src/app/shared/modals/food-rates/food-rates.component.spec.ts
- embc-app/ClientApp/src/app/shared/modals/food-rates/food-rates.component.ts
- embc-app/ClientApp/src/app/shared/modals/incidentals-rates/incidentals-rates.component.html
- embc-app/ClientApp/src/app/shared/modals/incidentals-rates/incidentals-rates.component.scss
- embc-app/ClientApp/src/app/shared/modals/incidentals-rates/incidentals-rates.component.spec.ts
- embc-app/ClientApp/src/app/shared/modals/incidentals-rates/incidentals-rates.component.ts
- embc-app/ClientApp/src/app/shared/modals/lodging-rates/lodging-rates.component.html
- embc-app/ClientApp/src/app/shared/modals/lodging-rates/lodging-rates.component.scss
- embc-app/ClientApp/src/app/shared/modals/lodging-rates/lodging-rates.component.spec.ts
- embc-app/ClientApp/src/app/shared/modals/lodging-rates/lodging-rates.component.ts
- embc-app/ClientApp/src/app/shared/modals/session-expiring/session-expiring.component.html
- embc-app/ClientApp/src/app/shared/modals/transportation-rates/transportation-rates.component.html
- embc-app/ClientApp/src/app/shared/modals/transportation-rates/transportation-rates.component.scss
- embc-app/ClientApp/src/app/shared/modals/transportation-rates/transportation-rates.component.spec.ts
- embc-app/ClientApp/src/app/shared/modals/transportation-rates/transportation-rates.component.ts
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/styles.scss
- embc-app/ClientApp/src/styles/components/tables.scss
- sql-server/README.md
> implemented ESS Rates components

- embc-app/ClientApp/src/app/self-registration/self-registration-error/self-registration-error.component.html
This makes the app look half-baked if anyone sees this error. I have requested the official version but this should be okay while we don't have the confirmed verbiage.
> Remove lorem ipsum

- embc-app/DataInterfaces/ViewModelConversions.IncidentTask.cs
- embc-app/Seeder/SeedData/IncidentTasks.json
- embc-app/Seeder/SeederRepository.cs
> Added seed start date to incident tasks and changed returned dates to UTC

- embc-app/ClientApp/.env-example
- embc-app/ClientApp/.env-sample
- embc-app/ClientApp/docker-compose.yml
- embc-app/ClientApp/src/proxy.conf.js
Use cookie to authenticate with remote API instead of a header
> Update authentication for local development

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.html
- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.scss
- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.spec.ts
- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.ts
- embc-app/ClientApp/src/app/core/models/address.model.ts
- embc-app/ClientApp/src/app/core/models/referral.model.ts
- embc-app/ClientApp/src/app/core/models/search-interfaces.ts
- embc-app/ClientApp/src/app/core/models/supplier.model.ts
- embc-app/ClientApp/src/app/core/services/referral.service.spec.ts
- embc-app/ClientApp/src/app/core/services/referral.service.ts
- embc-app/ClientApp/src/app/core/services/registration.service.ts
- embc-app/ClientApp/src/app/registration-list/registration-list.component.html
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.html
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.ts
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/referral-table/referral-table.component.html
- embc-app/ClientApp/src/app/volunteer/components/referral-table/referral-table.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.spec.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.ts
This feature will need a bit more work when the BE is complete, however it is functional enough for now to review and integrate (for dev use only).
> referrals table + other model/component/service changes

- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.html
- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.scss
- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.ts
-fixed table styling
-updated 'view' links
-misc cleanup
> referral table cleanup

- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/registration-list/registration-list.component.ts
- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.ts
- embc-app/ClientApp/src/app/registration-summary-full/registration-summary-full.component.ts
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.ts
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/components/referral-table/referral-table.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.ts
(some of these were inadvertently removed by EMBCESS-625)
> added some checks for bad server responses

- embc-app/ClientApp/docker-rebuild.sh
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/core/models/incident-task.model.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.scss
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.scss
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.html
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.scss
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.spec.ts
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.ts
- embc-app/ClientApp/src/app/shared/shared.module.ts
- embc-app/ClientApp/src/app/store/incident-tasks/incident-tasks.reducer.ts
- embc-app/ClientApp/src/app/volunteer/components/referral-table/referral-table.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
* Create **DateTimePicker** sub-component
* Update IncidentTask frontend model
* Form changes to accommodate new fields
* Replace browse alert box with proper Form validation messages
> EMBCESS-549 As a provincial admin, I want to provide date and time when adding a task number

- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.ts
- embc-app/ClientApp/src/app/core/services/referral.service.ts
- embc-app/ClientApp/src/app/volunteer/components/referral-table/referral-table.component.html
- embc-app/ClientApp/src/app/volunteer/components/referral-table/referral-table.component.ts
-implemented "show deactivated referrals" (prepare for EMBCESS-664)
-finished "select referrals to print" (prepare for EMBCESS-665)
> addl work on referrals list

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.html
- embc-app/ClientApp/src/app/core/services/auth.service.ts
This is a cleanup task to remove hyphens from FE routes
> Remove hyphens from routes

- embc-app/ClientApp/package-lock.json
- embc-app/ClientApp/package.json
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration.component.scss
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.html
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.scss
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.ts
- embc-app/ClientApp/src/app/shared/pipes/date-time-format.pipe.ts
- embc-app/ClientApp/src/app/shared/shared.module.ts
- embc-app/ClientApp/src/app/volunteer/components/valid-from-to/valid-from-to.component.scss
- updated date-time-picker to use masked inputs
- fixed date-time-format pipe
- WIP so others can clone the new code
- still to come: valid-from-to component refactor
> updated date-time-picker to use masked inputs (WIP)

- embc-app/ClientApp/src/app/shared/shared.module.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
> restored NgbTimepickerModule (WIP)

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/core/services/registration.service.ts
- embc-app/ClientApp/src/app/registration-summary-full/registration-summary-full.component.ts
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.html
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
-implemented "reason for view" codes
-passed reason to API call
-fixed some null select options
-fixed some routing expected roles
-changed referral maker to use summary instead of full reg
> added "reason for view" codes to API call

- embc-app/ClientApp/src/app/core/services/organization.service.ts
- embc-app/ClientApp/src/app/core/services/volunteer.service.ts
- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/volunteer-organization-list/volunteer-organization-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/volunteer-organization-list/volunteer-organization-list.component.ts
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.ts
- embc-app/ClientApp/src/app/volunteer-list/volunteer-list.component.html
- embc-app/ClientApp/src/app/volunteer-list/volunteer-list.component.ts
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.ts
- embc-app/ClientApp/src/styles.scss
-added modals to confirm editing user
-vertically centered some modals
-changed some modals to smaller size
-fixed some anchor hrefs and buttons
-fixed 'add users' invalid key
-fixed some lint errors
> prompt when editing user + misc fixes (see details)

- embc-app/ClientApp/src/app/provincial-admin/components/volunteer-organization-list/volunteer-organization-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/volunteer-organization-list/volunteer-organization-list.component.ts
- embc-app/ClientApp/src/app/registration-list/registration-list.component.html
- embc-app/ClientApp/src/app/registration-list/registration-list.component.ts
- embc-app/ClientApp/src/app/volunteer-list/volunteer-list.component.html
- embc-app/ClientApp/src/app/volunteer-list/volunteer-list.component.ts
> comment out pagination

- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/registration-summary-full/registration-summary-full.component.html
- embc-app/ClientApp/src/app/registration-summary-full/registration-summary-full.component.ts
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.html
-always display Family Recovery Plan, Referrals Made Within Reception Centre, Other Agency Referrals and Internal Case Notes on full profile page
-fixed date and time format example
> quick UI fixes (see details)

- embc-app/ClientApp/src/app/shared/components/captcha/captcha.component.html
Please ignore whitespace changes. I blame VS Code.
The actual change is on line 143.
> changed Captcha event to support touchscreen devices

- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/shared/directives/upper-case.directive.ts
- embc-app/ClientApp/src/app/shared/shared.module.ts
NB - I used CSS to display the input as uppercase and then I used the directive on the blur event (ie, once only -- not every character) to convert the input.
> implemented directive to make Last Name inputs upper case

- embc-app/ClientApp/src/app/shared/pipes/date-time-format.pipe.ts
- embc-app/ClientApp/src/app/volunteer/components/abstract-referral/abstract-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/referral-list-item/referral-list-item.component.html
- embc-app/ClientApp/src/app/volunteer/components/referral-list-item/referral-list-item.component.scss
- embc-app/ClientApp/src/app/volunteer/components/referral-list-item/referral-list-item.component.ts
- embc-app/ClientApp/src/app/volunteer/components/supplier/supplier.component.ts
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/valid-from-to/valid-from-to.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/styles.scss
- embc-app/ClientApp/src/styles/components/summary.scss
increased referral blue header height
made primary and secondary buttons looks like wireframes
fixed card borders + comments styling
food referral styling
removed seconds from date-time pipe
delete supplier tel or fax if value is empty
finished food referral (except validation) + more styling
improved referral responsiveness
> food referral, etc

- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.scss
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.scss
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/referral-list-item/referral-list-item.component.html
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
- embc-app/ClientApp/src/styles.scss
- embc-app/ClientApp/src/styles/_defaults.scss
- embc-app/ClientApp/src/styles/components/summary.scss
also fixed Firefox select button style
also added style helpers
also replaced unsupported CSS variables
also fixed some text
> fixed IE/Edge layout issues

- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/styles/components/summary.scss
- updated valid-from-to widths for various breakpoints (re: View Referral page)
- upper-cased evacuee last names on form load
> minor fixes

- embc-app/Controllers/ReferralsController.cs
- embc-app/Services/Referrals/IReferralsService.cs
- embc-app/Services/Referrals/ReferralsService.cs
- embc-unit-tests/ReferralsServicesTests.cs
> EMBCESS 555: referral type validation

- TRAINING-Jenkinsfile
- embc-app/ClientApp/src/app/core/guards/logged-in.guard.ts
- embc-app/ClientApp/src/app/home/home.component.html
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.html
- embc-app/ClientApp/src/app/shared/components/header/header.component.html
- embc-app/Migrations/20190506213507_EvacueeRegistration-Evacuee-EvacueeAddress-Tables.cs
@catspublish @CodingVelocista  please review and merge when ready
> Changes in master merging into develop

- embc-app/ClientApp/src/app/volunteer/components/abstract-referral/abstract-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.ts
also fixed dropdown reduction calculations
> fixed Maximum Amount calculations

- embc-app/Services/Referrals/Views/Groceries/GroceriesChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Incidentals/IncidentalsChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Meals/MealsChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Meals/MealsItemsPartial.hbs
- embc-app/Services/Referrals/Views/Referral.hbs
- embc-app/Services/Referrals/Views/SummaryItem.hbs
- embc-app/Services/Referrals/Views/Taxi/TaxiChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Taxi/TaxiItemsPartial.hbs
[EMBCESS-774] fixed invalid characters in PDF
[EMBCESS-775] fixed typo and case
[EMBCESS-776] added missing supplier province
[EMBCESS-771] fixed typo
[EMBCESS-769] fixed taxi To/From layout
> fixed misc PDF errors

- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.ts
- embc-app/ClientApp/src/styles.scss
- also removed red 'X when select is invalid
Notes:
- if code fails to load the main object for the page, go back to main dashboard
- if code fails to do something with an object on the page, stay on the page
> added some error notifications

- embc-app/Services/Referrals/Views/Billeting/BilletingChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Clothing/ClothingChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Groceries/GroceriesChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Hotel/HotelChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Incidentals/IncidentalsChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Meals/MealsChecklistPartial.hbs
- embc-app/Services/Referrals/Views/Taxi/TaxiChecklistPartial.hbs
- moved long lines to same row (to prevent weird bullet spacing)
- changed & to &amp; (best practice)
> rearranged PDF checklists so bullets line up better

- embc-app/ClientApp/src/app/volunteer/components/abstract-referral/abstract-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.ts
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.ts
also includes Food referral fixes
> referral validation: transportation, incidentals and clothing and lodging

- embc-app/ClientApp/src/app/app.component.ts
It was very hard to develop when the application kicks me out and does weird things. This prevents forcing the user out.
> Disable routing block for "dev (" environments

- embc-app/ClientApp/src/app/core/models/referral.model.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.ts
I also deleted an obsolete referral model variable.
Tested locally!
> fixed referral id on get

- embc-app/ClientApp/src/app/components/referral-search-results/referral-search-results.component.ts
- embc-app/ClientApp/src/app/components/sidebox-add-organization/sidebox-add-organization.component.ts
- embc-app/ClientApp/src/app/components/sidebox-add-registration/sidebox-add-registration.component.ts
- embc-app/ClientApp/src/app/components/sidebox-add-task-number/sidebox-add-task-number.component.ts
- embc-app/ClientApp/src/app/components/sidebox-add-volunteer/sidebox-add-volunteer.component.ts
- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.ts
- embc-app/ClientApp/src/app/core/services/auth.service.ts
- embc-app/ClientApp/src/app/core/services/watchdog.service.ts
- embc-app/ClientApp/src/app/local-authority/components/volunteer-list/volunteer-list.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/organization-list/organization-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/organization-list/organization-list.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-list/task-number-list.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/volunteer-organization-list/volunteer-organization-list.component.ts
- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.ts
- embc-app/ClientApp/src/app/registration-summary-full/registration-summary-full.component.ts
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.ts
- embc-app/ClientApp/src/app/shared/components/address-form/address-selector.component.ts
- embc-app/ClientApp/src/app/shared/components/captcha/captcha.component.ts
- embc-app/ClientApp/src/app/shared/components/environment-banner/environment-banner.component.ts
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.html
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.ts
-changed volunteer maker to FormGroup with validation
-fixed some routing params
-redirect to org list when fail to get org
-added some missing routing ids
-fixed some anchors
-misc cleanup
-added typings to subscription responses
> volunteer maker validation

- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.html
- embc-app/ClientApp/src/app/volunteer/components/supplier/supplier.component.html
- embc-app/ClientApp/src/app/volunteer/components/valid-from-to/valid-from-to.component.html
THIS HAS BEEN APPROVED TO GO INTO MASTER BY AMB.
> prevented clicking in middle of mask

- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.scss
Bullet fix at customer request.
> indentation tweak

- embc-app/DataInterfaces/EmbcDbContext.cs
- embc-app/Services/Registrations/AuditService.cs
(cherry picked from commit b095630f1bfc0b65ac979ae42471a69c05394b8b)
> Changed audit user id claim type to ClaimTypes.Sid

- TRAINING-Jenkinsfile
(cherry picked from commit 4856dd7136c768178b1bb4a5245c3ab46d97047e)
> Add quotes in build call in Training-Jenkins (#565)

- embc-app/ClientApp/src/app/volunteer/components/valid-from-to/valid-from-to.component.html
- embc-app/ClientApp/src/app/volunteer/components/valid-from-to/valid-from-to.component.ts
cleanup = deleted obsolete Edit Mode
> editable To time + cleanup

- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/shared/components/date-time-picker/date-time-picker.component.html
- embc-app/ClientApp/src/app/volunteer/components/supplier/supplier.component.html
- embc-app/ClientApp/src/app/volunteer/components/valid-from-to/valid-from-to.component.html
duplicate PR to merge this code into 'develop' branch
> (develop) prevented clicking in middle of mask

- embc-app/ClientApp/src/app/volunteer/components/evacuee-picker/evacuee-picker.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-picker/evacuee-picker.component.scss
> Scroll if over five family members

- embc-app/Services/Referrals/Views/Css.hbs
- embc-app/Services/Referrals/Views/Referral.hbs
* Add more space to signature field
* Lighten watermark "Place stamp here"
Fixes EMBCESS-897 and EMBCESS-895
> PDF tweaks

- embc-app/DataInterfaces/DataInterface.Evacuee.cs
> Change evacuee search query to a "contains" on last name

- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.ts
I made this substantially similar to the self-registration form.
There will be another Jira task to make restrictedAccess mandatory (and false by defaut) in BE.
> set active form on edit/finalize an evacuee

- embc-app/ClientApp/src/app/provincial-admin/components/organization-list/organization-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.html
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.html
it appears that button placement is fine. I adjusted unusual widths as well.
> Button placement

- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/registration-summary-full/registration-summary-full.component.html
- embc-app/ClientApp/src/app/registration-summary/registration-summary.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
- embc-app/ClientApp/src/app/shared/components/environment-banner/environment-banner.component.scss
- embc-app/ClientApp/src/app/shared/components/header/header.component.html
- embc-app/ClientApp/src/app/shared/components/header/header.component.scss
- embc-app/ClientApp/src/app/shared/components/side-box-info/side-box-info.component.html
- embc-app/ClientApp/src/app/shared/components/side-box-info/side-box-info.component.scss
- embc-app/ClientApp/src/app/volunteer-maker/volunteer-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/referral-table/referral-table.component.html
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-view/referral-view.component.html
- embc-app/ClientApp/src/styles.scss
- embc-app/ClientApp/src/styles/components/tables.scss
- fixed 'secondary' button
- updated reg summary page
- updated env banner, header and sideboxes
- updated table line height
- updated global header sizes
> more styling

- embc-app/ClientApp/src/app/app.component.html
- embc-app/ClientApp/src/app/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/registration-summary-full/registration-summary-full.component.html
- embc-app/ClientApp/src/app/shared/components/header/header.component.scss
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/clothing-referral/clothing-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/food-referral/food-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/incidentals-referral/incidentals-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.html
- embc-app/ClientApp/src/app/volunteer/components/transportation-referral/transportation-referral.component.scss
- embc-app/ClientApp/src/app/volunteer/components/valid-from-to/valid-from-to.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
- embc-app/ClientApp/src/styles.scss
- embc-app/ClientApp/src/styles/components/feature-blocks.scss
- embc-app/ClientApp/src/styles/components/form-elements.scss
- embc-app/ClientApp/src/styles/components/spinner.scss
- embc-app/ClientApp/src/styles/components/summary.scss
- updated some global form and feature block fields
- extended BS display-x styles
- removed spinners from number inputs
- removed superfluous div from app component
- updated some reg maker sizes and whitespace
- updated some referral padding
- updated evacuee list whitespace
- updated valid-from-to sizes
- updated some referral maker sizes
- fixed referral fixed-size size
> more styling (forms, reg maker, ref maker, etc)

- embc-app/ClientApp/src/app/core/interceptors/unauthorized.interceptor.ts
- embc-app/ClientApp/src/app/core/models/config.model.ts
- embc-app/ClientApp/src/app/core/services/auth.service.ts
- embc-app/ClientApp/src/app/core/services/controlled-list.service.ts
- embc-app/ClientApp/src/app/core/services/cookie.service.ts
- embc-app/ClientApp/src/app/core/services/rest.service.ts
- embc-app/ClientApp/src/app/core/services/watchdog.service.ts
- embc-app/ClientApp/src/app/tester-page/tester-page.component.html
- embc-app/ClientApp/src/app/tester-page/tester-page.component.ts
Reverts bcgov/embc-ess#636
logout redirected to dev.justice.gov.bc.ca/logout instead of the appropriate logout link.
> Revert "Timeout experiment"

- embc-app/ClientApp/src/app/core/models/evacuee.model.ts
- embc-app/ClientApp/src/app/core/models/search-interfaces.ts
- embc-app/ClientApp/src/app/core/services/evacuee.service.ts
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.ts
> Evacuee advanced search (Frontend)

- embc-app/ClientApp/src/app/shared/components/captcha/captcha.component.ts
> Revert "Captcha audio workaround for Safari"

- embc-app/Services/Referrals/Views/Billeting/BilletingItemsPartial.hbs
- embc-app/Services/Referrals/Views/Css.hbs
- embc-app/Services/Referrals/Views/Groceries/GroceriesItemsPartial.hbs
- embc-app/Services/Referrals/Views/Hotel/HotelItemsPartial.hbs
- embc-app/Services/Referrals/Views/Meals/MealsNotesPartial.hbs
- embc-app/Services/Referrals/Views/Transportation/TransportationItemsPartial.hbs
- also increased padding on summary first column
- also deleted extra whitespace
> fixed summary notes word breaking

- embc-app/ClientApp/src/app/core/interceptors/unauthorized.interceptor.ts
- embc-app/ClientApp/src/app/core/services/auth.service.ts
- embc-app/ClientApp/src/app/core/services/rest.service.ts
Try `document.location.href = 'logout';` to get siteminder to leave the app on logout.
> Logout experiment

- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
NB - I will revert this if it doesn't work.
> preload Captcha audio (needed by Safari/iOS)

- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.scss
- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.ts
This is for the Organization Maker page.
> changed over form validation to new way

- embc-app/ClientApp/src/app/volunteer/components/referral-list-item/referral-list-item.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/styles.scss
- embc-app/ClientApp/src/styles/components/feature-blocks.scss
- embc-app/ClientApp/src/styles/components/form-elements.scss
- headers now flow h1 -> h2 -> h3
- Override Start Time is now part of Incident Start Time block and wraps as needed
- vertical spacing between blocks is consistent and looks good
- labels are correctly sized and bolded
- checkboxes are better aligned with their label
- "display-X" styles now override any other styles
- feature block header left/right padding is now consistent with feature block padding
> referral layout updates per wireframes

- embc-app/ClientApp/src/app/volunteer/components/lodging-referral/lodging-referral.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
Also fixed incorrect Bootstrap column styles in other pages.
> set default numRooms to 1 + removed 'null' option

- embc-app/ClientApp/src/app/shared/utils/environment-utils.spec.ts
- embc-app/ClientApp/src/app/shared/utils/environment-utils.ts
> Update IE10 detection code so it doesn't trigger a CSP violation

- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.html
- embc-app/ClientApp/src/app/components/top-tab-bar/top-tab-bar.component.html
- embc-app/ClientApp/src/app/components/top-tab-bar/top-tab-bar.component.spec.ts
- embc-app/ClientApp/src/app/components/top-tab-bar/top-tab-bar.component.ts
- embc-app/ClientApp/src/app/shared/components/captcha/captcha.component.html
> Revert "implemented menubar toggle + other stuff"

- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.html
- embc-app/ClientApp/src/app/shared/components/communities-select/communities-select.component.ts
I also changed the Task Number Maker so that pressing Enter in an input does not attempt to submit the page -- the user must click the Next button.
> added communities-select Enter event handler with partial match feature

- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.html
- embc-app/ClientApp/src/app/core/models/registration.model.ts
- embc-app/ClientApp/src/app/store/registration/registration.reducer.ts
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
Tested against changes to API in sandbox. Works. Builds fine.
> Add pets to FE code

- .dockerignore
- docker-compose.yml
- embc-app/.vscode/launch.json
- embc-app/Directory.Build.props
- embc-app/Dockerfile
- embc-app/embc-app.csproj
- sql-server/Dockerfile
- sql-server/docker-compose.yml
* enable remote debugging into API docker container
* skip ANGULAR build in docker
* add DB container (in docker-compose.yml)
* add debug configuration for VS Code
> Docker containers for backend API, database

- embc-app/ConfigurationEx.cs
- embc-app/Startup.cs
…ag to disable the policy (#724)
* Replaced CSP middleware with custom hand crafted header and config flag to disable the policy
* spelling
> merge Sandbox->Develop

- embc-app/ClientApp/src/app/registration-summary-full/registration-summary-full.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.ts
The checkboxes were inconsistent across the application. 
Change to a consistent order application-wide. (FCLIT)
Food
Clothing 
Lodging 
Incidentals 
Transportation
> Checkbox ordering consistency

- embc-app/Startup.cs
- embc-app/embc-app.csproj
- embc-app/swagger.json
Automatically generated API documentation.
> Add NSwag for API documentation

- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/app/volunteer/pages/referral-maker/referral-maker.component.scss
> Referral maker numbering

- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.ts
> Fix pagination issue on evacuee search

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
* Add wording to Self-Reg
* Update the wording when the volunteer registers an evacuee
> Update primary residency language

- embc-app/Controllers/VolunteersController.cs
Fixed duplicate check when updating volunteer to allow update when bceid is not changed
> EMBCESS-1042: bug fix to volunteer update

- embc-app/Controllers/ReportsController.cs
- embc-app/Services/Registrations/RegistrationQueryService.cs
- embc-unit-tests/Registrations/ViewRegistrationTests.cs
* Updated view audit reason text
* Fixed date format in CSV output
* Fixed unit test to compare UTC
> EMBCESS-843: Updated view audit reason text

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/core/services/audit.service.spec.ts
- embc-app/ClientApp/src/app/core/services/audit.service.ts
- embc-app/ClientApp/src/app/provincial-admin/components/auditor/auditor.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/auditor/auditor.component.spec.ts
- embc-app/ClientApp/src/app/provincial-admin/components/auditor/auditor.component.ts
This is a developer place to go look at access data and download the csv.
> handy audit

- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
Minor changes. 
Before this PR I updated r1develop without a pull request (my mistake)
> Cosmetic updates to EMBCESSMOD-132

- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.ts
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
- embc-app/ClientApp/src/styles.scss
EMBCESSMOD-133 - Needs Assessment (Volunteer View) - Angular
> Needs Assessment (Volunteer View)

- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
Added tabindex="0" attribute to enable tabbing to radio buttons when registering an evacuee.
> Embcessmod 85

- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
Updated text in restriction blurb when a volunteer is creating an evacuee.
> Updated text when a volunteer creates an evacuee

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
Changed wording to match the wire frame.
> Updated self-registration restriction blurb.

- embc-app/Services/Referrals/Views/Transportation/TransportationChecklistPartial.hbs
Essentially took the Checklist part from TaxiChecklistPartial and added it to TransportationChecklistPartial but deleted the row that specifically mentions the Taxi driver.
> Add checklist to Transport_Other referral pdf

- README.md
- embc-app/Authentication/KeyCloakClaimTransformer.cs
- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/core/guards/landing-page.guard.ts
- embc-app/Controllers/LoginController.cs
- embc-app/Controllers/LogoutController.cs
- embc-app/Startup.cs
This PR also contains changes to the name claim due to discrepancies between KeyCloak Dev and Test environments
> Embcessmod 178 - enable and document how to access the API directly from local dev machine

- embc-app/Authentication/KeyCloakClaimTransformer.cs
- embc-app/ClientApp/src/app/app.component.ts
- embc-app/ClientApp/src/app/shared/components/footer/footer.component.html
- embc-app/ClientApp/src/app/shared/components/footer/footer.component.ts
- embc-app/Controllers/UsersController.cs
- embc-app/Seeder/SeedData/Volunteers.json
Addresses JIRA tickets EMBCESSMOD-184, 187, 189, 195
> EMBCESSMOD-184: various fixes

- embc-app/ClientApp/src/app/core/models/search-interfaces.ts
- embc-app/ClientApp/src/app/core/services/evacuee.service.ts
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.scss
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.ts
* Added front end to allow searching for evacuee by date of birth
* Added validation to prevent advance search unless all three fields have values
> Embcessmod 134 - Search Gate Angular

- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.ts
- embc-app/ClientApp/src/app/shared/modals/insurance-info/insurance-info.component.html
- embc-app/ClientApp/src/app/shared/modals/insurance-info/insurance-info.component.scss
- embc-app/ClientApp/src/app/shared/modals/insurance-info/insurance-info.component.spec.ts
- embc-app/ClientApp/src/app/shared/modals/insurance-info/insurance-info.component.ts
- embc-app/ClientApp/src/app/shared/shared.module.ts
* Added info modal when yes or yes-unsure is selected during self-registration
> Embcessmod 173 - Add insurance info pop up

- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
> Add see your ESS Supervisor text

- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.scss
Changed layout of registration details as per embcessmod-170
> Update layout of Registration Details

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
Was only done on the registration maker component before.
> Add tab-index to checkboxes on self-registration

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
* EMBCESSMOD-98
* Change contact to family member
> Change add contact to add family member

- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.scss
There are tons of changes with this PR because I used VS Code to auto format this file, which split up a bunch of long text onto multiple lines. Doesn't change how it's displayed, just makes it a bit easier to read. The actual changes I made in the HTML are from line 777 to 795.
> Embcessmod 170 review step angular

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
Last wording update for embcessmod 96 and 98.
> Clarify wording on adding another family member during self registration

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.scss
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.scss
- embc-app/ClientApp/src/styles.scss
Added tool tip explaining primary residence as per embcessmod-88.
Formatted document with VS Code, so long lines have been split up.
> Add tool tip about primary residence

- embc-app/ClientApp/src/app/self-registration/self-registration-two/self-registration-two.component.html
- embc-app/ClientApp/src/app/shared/modals/insurance-info/insurance-info.component.html
- embc-app/ClientApp/src/app/shared/modals/insurance-info/insurance-info.component.scss
* Added info modal to the 'Yes' option (missed it the first time)
* Changed styles on the modal to better match the wireframe
> EMBCESSMOD 173 - Insurance info pop up

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
Removed the validation for relationship to evacuee since I forgot to remove it when I removed the drop down :)
> Remove validation for relationship to evacuee

- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.scss
> Add link to home after self registration

- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-four/self-registration-four.component.scss
Changed button text to all caps
> Embcessmod 80 return home after reg

- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
> Add link to safety manual in useful information

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.scss
- embc-app/ClientApp/src/app/volunteer/pages/volunteer-evacuee-results-page/volunteer-evacuee-results-page.component.html
- embc-app/ClientApp/src/app/volunteer/pages/volunteer-evacuee-results-page/volunteer-evacuee-results-page.component.spec.ts
- embc-app/ClientApp/src/app/volunteer/pages/volunteer-evacuee-results-page/volunteer-evacuee-results-page.component.ts
For EMBCESS-MOD-134 Angular Search Gate
Added volunteer-evacuee-results-page component and changed routing to go there when a volunteer searches.
Rolled my face on the keyboard until the CSS sorta looked more like the wireframes.
> Embcessmod 134 search gate ui

- embc-app/ClientApp/src/app/shared/components/footer/footer.component.scss
Made the text white and changed cursor to be a pointer.
> Add style to app info link

- embc-app/Services/Referrals/Views/Taxi/TaxiChecklistPartial.hbs
* Changed checklist to match client specifications
> Change Taxi referral invoice checklist

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.html
- embc-app/ClientApp/src/app/core/models/incident-task.model.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-list/task-number-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/task-number-maker-page/task-number-maker-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/task-number-maker-page/task-number-maker-page.component.spec.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/task-number-maker-page/task-number-maker-page.component.ts
- embc-app/ClientApp/src/app/store/incident-tasks/incident-tasks.reducer.ts
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.ts
- embc-app/Controllers/IncidentTasksController.cs
- embc-app/Migrations/20200213222704_Add-Task-Number-Date-Fields-To-Incident-Task.Designer.cs
- embc-app/Migrations/20200213222704_Add-Task-Number-Date-Fields-To-Incident-Task.cs
- embc-app/Models/Db/EvacueeRegistration.cs
- embc-app/Models/Db/IncidentTask.cs
- embc-app/Utils/IncidentTaskHelper.cs
- embc-app/ViewModels/IncidentTask.cs
- embc-app/ViewModels/Registration.cs
* Changes related to EMBCESSMOD-233 and 236
* Added TaskNumberStartDate and TaskNumberEndDate columns to IncidentTasks
* Label changes for Host Community/Incident Location
> Embcessmod 233 & 236 task num changes

- embc-app/Services/Referrals/Views/Taxi/TaxiChecklistPartial.hbs
Had a rogue closing span tag in the partial.
> Fix error in taxi referral checklist

- embc-app/Authentication/KeyCloakClaimTransformer.cs
- embc-app/ClientApp/src/app/core/services/auth.service.ts
- embc-app/ClientApp/src/app/local-authority/components/volunteer-maker/volunteer-maker.component.html
- embc-app/ClientApp/src/app/local-authority/components/volunteer-maker/volunteer-maker.component.ts
- embc-app/Controllers/UsersController.cs
* Added checkbox control for admin access on volunteer maker
* Changed the BCeID local authority roles to be mapped based on isAdministrator rather than isPrimaryContact
> Embcessmod 251 user priv update

- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.ts
- embc-app/ClientApp/src/app/volunteer/components/evacuee-search-results/evacuee-search-results.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-search-results/evacuee-search-results.component.ts
* Added better null check for search results template
* Removed the parameter from updateDob() in search gate - template was calling the function without parameters
> Fix bugs breaking build

- embc-app/Services/Referrals/Views/Taxi/TaxiChecklistPartial.hbs
- embc-app/Utils/ICurrentUser.cs
Fixed duplicate item in the taxi referral checklist partial
> Embcessmod 83 taxi referral bug

- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.scss
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/task-number-maker-page/task-number-maker-page.component.html
- embc-app/Utils/ICurrentUser.cs
Removed incident fields, enabled editing of task number start date, renamed Host Community to Support Community.
> Embcessmod 255 new task num changes

- embc-app/ClientApp/src/app/components/registration-summary/registration-summary.component.html
- embc-app/ClientApp/src/app/components/registration-summary/registration-summary.component.scss
- embc-app/ClientApp/src/app/components/registration-summary/registration-summary.component.ts
- embc-app/ClientApp/src/app/core/services/incident-task.service.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-list/task-number-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-list/task-number-list.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/referral-maker/referral-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/referral-maker/referral-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
- embc-app/Controllers/IncidentTasksController.cs
- embc-app/DataInterfaces/DataInterface.IncidentTask.cs
- embc-app/DataInterfaces/IDataInterface.cs
* Added GetOpenIncidentTasks to IncidentTasksController
* Changed the client to call new function when getting task numbers for creating registrations.
* Added toggle to display active or inactive tasks in the task list
> Embcessmod 258 prevent referrals on closed task

- embc-app/ClientApp/src/app/components/registration-summary/registration-summary.component.ts
- embc-app/ClientApp/src/app/core/models/list-result.ts
- embc-app/ClientApp/src/app/core/models/open-and-closed-tasks-metadata.model.ts
- embc-app/ClientApp/src/app/core/services/incident-task.service.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-list/task-number-list.component.ts
Fixed the null reference bug in registration summary
Fixed a build issue with type script imports
> Terrifying registration bug

- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.scss
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
Removed the call to the function scrolling the form to first invalid control. Instead we're just listing what forms are missed.
> Change registration maker to list validation errors, remove scrolling

- embc-app/ClientApp/src/app/app-routing.module.ts
- embc-app/ClientApp/src/app/app.module.ts
- embc-app/ClientApp/src/app/components/registration-summary/registration-summary.component.scss
- embc-app/ClientApp/src/app/components/sidebox-add-organization/sidebox-add-organization.component.html
- embc-app/ClientApp/src/app/components/sidebox-add-volunteer/sidebox-add-volunteer.component.html
- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.html
- embc-app/ClientApp/src/app/home/home.component.html
- embc-app/ClientApp/src/app/home/home.component.scss
- embc-app/ClientApp/src/app/local-authority/components/local-authority-evacuee-list/local-authority-evacuee-list.component.html
- embc-app/ClientApp/src/app/local-authority/components/volunteer-maker/volunteer-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/admin-volunteer-maker/admin-volunteer-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/organization-list/organization-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-list/task-number-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/volunteer-organization-list/volunteer-organization-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/admin-volunteer-maker-page/admin-volunteer-maker-page/admin-volunteer-maker-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/admin-volunteer-maker-page/admin-volunteer-maker-page/admin-volunteer-maker-page.component.spec.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/admin-volunteer-maker-page/admin-volunteer-maker-page/admin-volunteer-maker-page.component.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/organization-maker-page/organization-maker-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/organizations-page/organizations-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/volunteers-organization/provincial-admin-volunteers-organization-page.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-stepper/self-registration-stepper.component.html
- embc-app/ClientApp/src/app/shared/modals/active-task/active-task.component.html
- embc-app/ClientApp/src/app/volunteer/components/evacuee-list/evacuee-list.component.html
Changed a ton of text to match approvals.
> Embcessmod 286 full system rewording

- embc-app/ClientApp/src/app/provincial-admin/components/task-number-list/task-number-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
* Added code to update the TaskNumberEndDate if a change to TaskNumberStartDate requires it
* Fixed the backwards logic for the display active/inactive tasks label
> Change task number maker to update end date when start date is modified

- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
The requested change for the previous PR
> Disable task selector in registration maker only for ERA User role

- embc-app/ClientApp/src/app/local-authority/pages/local-authority-registrations-page/local-authority-registrations-page.component.html
- embc-app/ClientApp/src/app/local-authority/pages/local-authority-registrations-page/local-authority-registrations-page.component.ts
- embc-app/ClientApp/src/app/local-authority/pages/local-authority-volunteers-page/local-authority-volunteers-page.component.html
- embc-app/ClientApp/src/app/local-authority/pages/local-authority-volunteers-page/local-authority-volunteers-page.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/admin-volunteer-maker/admin-volunteer-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/admin-volunteer-maker/admin-volunteer-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/admin-volunteer-maker-page/admin-volunteer-maker-page/admin-volunteer-maker-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/admin-volunteer-maker-page/admin-volunteer-maker-page/admin-volunteer-maker-page.component.ts
∩
　　　　　　　＼＼
　　　　　　　／　 ）
⊂＼＿／￣￣￣　 ／
　＼＿／   ° ͜ʖ ° （
　　　）　　 　／⌒＼
　　／　 ＿＿＿／⌒＼⊃
　（　 ／
　　＼＼
U
> Embcessmod 286 rewording

- embc-app/ClientApp/src/app/shared/validation/custom.validators.ts
This should be the final PR for this task! It really, really, really shouldn't be possible to have an end date before a start date now. 
_______oBBBBB8o______oBBBBBBB 
_____o8BBBBBBBBBBB__BBBBBBBBB8________o88o, 
___o8BBBBBB**8BBBB__BBBBBBBBBB_____oBBBBBBBo, 
__oBBBBBBB*___***___BBBBBBBBBB_____BBBBBBBBBBo, 
_8BBBBBBBBBBooooo___*BBBBBBB8______*BB*_8BBBBBBo, 
_8BBBBBBBBBBBBBBBB8ooBBBBBBB8___________8BBBBBBB8, 
__*BBBBBBBBBBBBBBBBBBBBBBBBBB8_o88BB88BBBBBBBBBBBB, 
____*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB8, 
______**8BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*, 
___________*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB8*, 
____________*BBBBBBBBBBBBBBBBBBBBBBBB8888**, 
_____________BBBBBBBBBBBBBBBBBBBBBBB*, 
_____________*BBBBBBBBBBBBBBBBBBBBB*, 
______________*BBBBBBBBBBBBBBBBBB8, …
> Change minDate validation precision from days to seconds

- embc-app/ClientApp/src/app/components/sidebox-add-volunteer/sidebox-add-volunteer.component.html
- embc-app/ClientApp/src/app/home/home.component.html
- embc-app/ClientApp/src/app/local-authority/components/local-authority-evacuee-list/local-authority-evacuee-list.component.html
- embc-app/ClientApp/src/app/local-authority/components/volunteer-list/volunteer-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/admin-volunteer-maker/admin-volunteer-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/admin-volunteer-maker/admin-volunteer-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/organization-list/organization-list.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.html
- embc-app/ClientApp/src/app/provincial-admin/components/organization-maker/organization-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/components/task-number-maker/task-number-maker.component.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/admin-registrations-page/admin-registrations-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/admin-registrations-page/admin-registrations-page.component.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/admin-volunteer-maker-page/admin-volunteer-maker-page/admin-volunteer-maker-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/organization-maker-page/organization-maker-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/organization-maker-page/organization-maker-page.component.ts
- embc-app/ClientApp/src/app/provincial-admin/pages/task-number-maker-page/task-number-maker-page.component.html
- embc-app/ClientApp/src/app/provincial-admin/pages/task-number-maker-page/task-number-maker-page.component.ts
- embc-app/ClientApp/src/app/shared/components/header/header.component.html
- embc-app/ClientApp/src/app/shared/components/header/header.component.ts
- embc-app/ClientApp/src/app/shared/modals/active-task/active-task.component.html
- embc-app/ClientApp/src/app/shared/modals/active-task/active-task.component.scss
▒▒▒▒▒▄██████████▄▒▒▒▒▒ 
▒▒▒▄██████████████▄▒▒▒ 
▒▒██████████████████▒▒ 
▒▐███▀▀▀▀▀██▀▀▀▀▀███▌▒ 
▒███▒▒▌■▐▒▒▒▒▌■▐▒▒███▒ 
▒▐██▄▒▀▀▀▒▒▒▒▀▀▀▒▄██▌▒ 
▒▒▀████▒▄▄▒▒▄▄▒████▀▒▒ 
▒▒▐███▒▒▒▀▒▒▀▒▒▒███▌▒▒ 
▒▒███▒▒▒▒▒▒▒▒▒▒▒▒███▒▒ 
▒▒▒██▒▒▀▀▀▀▀▀▀▀▒▒██▒▒▒ 
▒▒▒▐██▄▒▒▒▒▒▒▒▒▄██▌▒▒▒ 
▒▒▒▒▀████████████▀▒▒▒▒
> Big old text changes

- embc-app/ClientApp/src/app/shared/components/access-denied/access-denied.component.html
Changed wording to match wireframe
> Change wording for access denied page

- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
> Enable old scroll code on registration maker

- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
Changed Host Community to Evacuated From in registration maker
> Label tweaks

- embc-app/ClientApp/src/app/components/registration-summary/registration-summary.component.html
- embc-app/ClientApp/src/app/local-authority/components/local-authority-evacuee-list/local-authority-evacuee-list.component.html
> Label fixes

- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.html
- embc-app/ClientApp/src/app/shared/components/header/header.component.ts
- embc-app/ClientApp/src/app/shared/modals/active-task/active-task.component.html
- embc-app/ClientApp/src/app/shared/modals/active-task/active-task.component.scss
- embc-app/ClientApp/src/app/shared/modals/active-task/active-task.component.ts
- embc-app/ClientApp/src/app/store/incident-tasks/incident-tasks.reducer.ts
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
- embc-app/ClientApp/src/app/volunteer/pages/volunteer-registrations-page/volunteer-registrations-page.component.ts
- embc-app/Controllers/VolunteerTasksController.cs
- embc-app/DataInterfaces/DataInterface.IncidentTask.cs
- embc-app/DataInterfaces/EmbcDbContext.cs
- embc-app/Migrations/20200320230414_Fix-VolunteerTasks-Unique-Constraint.Designer.cs
- embc-app/Migrations/20200320230414_Fix-VolunteerTasks-Unique-Constraint.cs
- embc-app/ViewModels/IncidentTask.cs
* Combined some work for EMBCESSMOD-238 and 239
* Fixed the issue with values changing outside of Angular life cycle (Thanks Yossi!)
* Updated Active Task modal to match wireframes
* Changed unique constraint on VolunteerTasks to be composite (on VolunteerId and IncidentTaskId)
> Embcessmod active task number

- embc-app/ClientApp/src/app/volunteer/components/referral-maker/subcomponents/food-referral/food-referral.component.ts
I've applied a complex mathematical proof to determine the number number of meals allowed by food referrals. By using a non-linear regression algorithm we can get to the desired result of "0, 1, 2". 
I didn't bother commenting this in the code because the math I've used is so complicated that if you can't pick it up by looking at it you'll never understand it.
> Add one to number of food referrals

- embc-app/ClientApp/src/app/core/services/auth.service.ts
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.scss
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.ts
Layout changes for EMBCESSMOD-340
> Embcessmod 340 training vid html

- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.html
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
Fixed bugs I had in the useful information page for 340
> Fix useful info bugs

- embc-app/ConfigurationEx.cs
- embc-app/Startup.cs
> fix: switched from specific known proxy to known network in fwd header

- embc-app/ConfigurationEx.cs
- embc-app/Startup.cs
- embc-app/embc-app.csproj
- embc-unit-tests/ReferralsServicesTests.cs
- embc-unit-tests/TestBase.cs
- embc-unit-tests/embc-unit-tests.csproj
> Data Protection setup

- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.html
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.ts
* Added new link
* Changed old link
* Removed pathfinder from URLS
* Still hard coded 👎
> Embcessmod 348 update link

- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
> Fix typo in useful info link

- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.html
- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.ts
- embc-app/ClientApp/src/app/local-authority/components/local-authority-evacuee-list/local-authority-evacuee-list.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.scss
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.ts
- embc-app/ClientApp/src/app/shared/validation/custom.validators.ts
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.scss
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
Added new inputs for when evacuee cannot provide an email or phone number.
> Embcessmod 373 phone email update

- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.html
- embc-app/ClientApp/src/app/components/full-registration-summary-block/full-registration-summary-block.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.scss
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.ts
- embc-app/ClientApp/src/app/shared/validation/custom.validators.ts
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.html
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.scss
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
* Add new checkboxes to self registration
* Add custom validation for no email and phone
* Update review of self reg to show no email/phone number
* Add new validation for email and phone number to registration-maker
* Uncommented code
> R1.2 updates

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/volunteer/components/registration-maker/registration-maker.component.ts
* Fixed the issue where you couldn't continue with a phone number and email address
* Fixed issue where editing the registration of an evacuee with no email / address provided the check boxes would become unchecked
> Embcessmod 373 fixes

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.html
- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
- embc-app/ClientApp/src/app/self-registration/self-registration-three/self-registration-three.component.html
Added Evacuated From field to self evacuation registration
> Embcessmod 306 self reg evac from

- embc-app/ClientApp/src/app/constants/environments.ts
- embc-app/ClientApp/src/app/constants/index.ts
- embc-app/ClientApp/src/app/core/models/config.model.ts
- embc-app/ClientApp/src/app/shared/components/environment-banner/environment-banner.component.html
- embc-app/ClientApp/src/app/shared/components/environment-banner/environment-banner.component.scss
- embc-app/ClientApp/src/app/shared/components/environment-banner/environment-banner.component.ts
- embc-app/ConfigurationEx.cs
- embc-app/Controllers/ConfigController.cs
- embc-app/ViewModels/ConfigurationInfo.cs
* Added different banner background depending on the environment (as defined in the ASPNETCORE_ENVIRONMENT variable)
* Added new variable to control the message on the banner (APP_ENVIRONMENT_TITLE)
The new variable is expected to be an HTML string. For example, for the development site:
`<span>You are in the <strong>DEVELOPMENT</strong> version of the <strong>Evacuee Registration & Assistance Tool.</strong></span><br/><span><small>All information entered here will be treated as <strong>test</strong> data.</small></span>`
> Add different styles depending on env

- embc-app/ClientApp/src/app/shared/components/header/header.component.html
- embc-app/ClientApp/src/app/shared/components/header/header.component.ts
Added the modal to the Log In link
> Add environment modal to login link in header

- embc-app/ClientApp/src/app/shared/modals/log-in-environment/log-in-environment.component.ts
Prod and Test will now display the text in the wireframes - all other environments will just reuse the APP_ENVIRONMENT_TITLE variable's text.
> Change env modal text to match wireframes

- embc-app/ClientApp/src/app/shared/modals/log-in-environment/log-in-environment.component.html
- embc-app/ClientApp/src/app/shared/modals/log-in-environment/log-in-environment.component.ts
* Fix for 449 (I did all that work to create the correct string but I forgot to actually display it...)
> Display correct env modal body text

- embc-app/Migrations/20200604225220_Duplicate_Self_Registrations_Fix.Designer.cs
- embc-app/Migrations/20200604225220_Duplicate_Self_Registrations_Fix.cs
> Add migration to fix view

- embc-app/ClientApp/src/app/shared/components/environment-banner/environment-banner.component.html
- embc-app/ClientApp/src/app/shared/components/environment-banner/environment-banner.component.scss
- embc-app/ClientApp/src/app/shared/components/environment-banner/environment-banner.component.ts
Added code to hide the environment banner when in the production environment and doing a self-registration.
> Hide env banner for prod self-reg

- embc-app/ClientApp/src/app/self-registration/self-registration-one/self-registration-one.component.ts
* Fixed issue where editing 'Are you being evacuated from your primary residence?' would result in Evacuated From being null
* Fixed issue where editing the self registration would null out the Evacuated From field
* Fixed issue where form was invalid when in fact it was not
> Embcessmod 306 fixes

- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.html
- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.scss
- embc-app/ClientApp/src/app/components/top-navbar/top-navbar.component.ts
Added contact info to nav bar: embecessmod-490
> Embcessmod 490 add contact info

- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
Updated header language on training and materials page for embcessmod-491
> Update language on training and material page

- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
Added new links to training materials
> Embcessmod 441 additional train mats

- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
Added link to release notes on useful information page
> Embcessmod 475 release notes

- embc-app/DataInterfaces/DataInterface.Evacuee.cs
* Removed unused search parameters
* Converted the DOB from query to a date before comparing it to the search query params
> Export fixes

- embc-app/ClientApp/src/app/core/models/app-version.model.ts
- embc-app/ClientApp/src/app/shared/modals/app-version/app-version.component.html
- embc-app/Controllers/ApplicationVersionInfoController.cs
- embc-app/Controllers/ConfigController.cs
- embc-app/ViewModels/ApplicationVersionInfo.cs
* For EMBCESSMOD-595
* Removed test code and implemented version 3
> Remove test code and implement file version 3

- embc-app/ClientApp/src/app/shared/modals/app-version/app-version.component.html
- embc-app/ClientApp/src/app/shared/modals/app-version/app-version.component.ts
- embc-app/Controllers/ApplicationVersionInfoController.cs
* Changed variable used for environment 
* Hide reference, repo, and commit to unauthenticated users
> Embcessmod 600 app version changes

- embc-app/ClientApp/src/app/core/models/app-version.model.ts
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.ts
- embc-app/Controllers/ApplicationVersionInfoController.cs
- embc-app/Controllers/ConfigController.cs
- embc-app/ViewModels/ApplicationVersionInfo.cs
- embc-app/ViewModels/ConfigurationInfo.cs
* Added Admin User Guide for Admin users
* Changed the release notes link from hard coded value to use RELEASE_VERSION variable
> Add admin training guide & use RELEASE_VERSION for release notes link

- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.html
- embc-app/ClientApp/src/app/volunteer/pages/useful-information-page/useful-information-page.component.ts
Changed the role names to be even more specific to match the wireframes.
> Embcessmod 602 useful info update
